<a href="https://colab.research.google.com/github/Siyatell/siyademo/blob/main/Aditya_Kumar_102203602_1st.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


arr=np.array([1,2,3,4,5])
res = np.flip(arr)
print("Final array", str(res))


Final array [5 4 3 2 1]


In [ ]:
import numpy as np

array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flat = array1.flatten()
print(flat)

[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)

True


In [2]:
import numpy as np

x=np.array([1,2,3,4,5,1,2,1,1,1])
print("Most frequent value in above array")
x_count = np.bincount(x)
x_maxf=np.argmax(x_count)
x_indices=np.where(x==x_maxf)[0]
print(x_maxf, x_indices)

y=np.array([1,1,1,2,3,4,2,4,3,3])
print("Most frequent value in above array")
y_count = np.bincount(y)
y_maxf=np.argmax(y_count)
y_indices=np.where(y==y_maxf)[0]
print(y_maxf, y_indices)

Most frequent value in above array
1 [0 5 7 8 9]
Most frequent value in above array
1 [0 1 2]


In [3]:
import numpy as np

gfg=np.matrix('[4,1,9;12 3 1; 4,5,6]')
sum = gfg.sum()
print(sum)

print("Sum of each column:")
print(np.sum(gfg, axis=0))

print("Sum of each row:")
print(np.sum(gfg, axis=1))

45
Sum of each column:
[[20  9 16]]
Sum of each row:
[[14]
 [16]
 [15]]


In [4]:
import numpy as np

n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
trace = np.trace(n_array)
print("Sum of Diagonal elements=")
print(trace)

evalue, evect = np.linalg.eig(n_array)
print("Eigen Values=")
print(evalue)
print("")
print("Eigen Vectors=")
print(evect)

inv = np.linalg.inv(n_array)
print("Inverse of Matrix=")
print(inv)

deter=np.linalg.det(n_array)
print("Determinant=")
print(deter)

Sum of Diagonal elements=
176
Eigen Values=
[98.16835147 28.097044   49.73460452]

Eigen Vectors=
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of Matrix=
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant=
137180.0000000001


In [5]:
import numpy as np

p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

result = np.dot(p, q)
print("The matrix multiplication is :")
print(result)

covar=np.cov(p,q)
print("\nCovariance matrix of the two arrays:\n", covar)

The matrix multiplication is :
[[16 19]
 [26 31]]

Covariance matrix of the two arrays:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [6]:
import numpy as np

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("\nInner product of matrices x and y =")
print(np.inner(x, y))
print("\nOuter product of vectors a and b =")
print(np.outer(x, y))
print("\nCross product of matrices x and y =")
print(np.cross(x, y))


Inner product of matrices x and y =
[[17 52]
 [13 62]]

Outer product of vectors a and b =
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cross product of matrices x and y =
[[-20   4   7]
 [-84  36  20]]


In [7]:
import numpy as np

array = np.array([[1, -2, 3],[-4, 5, -6]])

abs_values = np.abs(array)
print("Element-wise absolute values:\n", abs_values)

Element-wise absolute values:
 [[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

percentiles_flattened = np.percentile(array, [25, 50, 75])

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("Flattened array percentiles:")
print(f"25th: {percentiles_flattened[0]}")
print(f"50th (Median): {percentiles_flattened[1]}")
print(f"75th: {percentiles_flattened[2]}\n")

print("Column-wise percentiles:")
print(f"25th: {percentiles_columns[0]}")
print(f"50th (Median): {percentiles_columns[1]}")
print(f"75th: {percentiles_columns[2]}\n")

print("Row-wise percentiles:")
print(f"25th: {percentiles_rows[0]}")
print(f"50th (Median): {percentiles_rows[1]}")
print(f"75th: {percentiles_rows[2]}")

Flattened array percentiles:
25th: -3.5
50th (Median): -0.5
75th: 2.5

Column-wise percentiles:
25th: [-2.75 -0.25 -3.75]
50th (Median): [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]

Row-wise percentiles:
25th: [-0.5 -5. ]
50th (Median): [ 1. -4.]
75th: [2.  0.5]


In [9]:
import numpy as np

# Flattened array statistics
flattened_array = array.flatten()
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

# Column-wise statistics
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

# Row-wise statistics
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Flattened array statistics:")
print(f"Mean: {mean_flattened}")
print(f"Median: {median_flattened}")
print(f"Standard Deviation: {std_flattened}\n")

print("Column-wise statistics:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Standard Deviation: {std_columns}\n")
print("Row-wise statistics:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Standard Deviation: {std_rows}")

Flattened array statistics:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise statistics:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Row-wise statistics:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [10]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
ceiling = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)
print("Floor values:", floor)
print("Ceiling values:", ceiling)
print("Truncated values:", truncated)
print("Rounded values:", rounded)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]
